---
title: "StatsBombR"
output: html_document
date: '2022-09-30'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
library(dplyr)
library(tidyverse)
library(StatsBombR)
```

```{r}
fc <- FreeCompetitions()
```

```#{r, warning=FALSE}
euro2020 <- fc %>%
  filter(competition_id==53)

euro2020matches <- FreeMatches(euro2020)

euro2020data <- free_allevents(MatchesDF = euro2020matches, Parallel = T)
```

```{r, warning=FALSE}
euro2022 <- fc %>%
  filter(competition_id==53)

euro2022matches <- FreeMatches(euro2022)

euro2022data <- free_allevents(MatchesDF = euro2022matches, Parallel = T)
```

```{r}
colnames(euro2022data)
```

```{r}
nrow(table(euro2022data$match_id))
length(table(euro2022data$match_id))
```

```{r, warning=FALSE}
lineups <- euro2020data %>%
  filter(type.name == "Starting XI")
```

```{r}
table(lineups$period)
```

```{r}
teams <- lineups %>%
  group_by(team.name) %>%
  summarize(n())

sum(teams$`n()`)
```
```{r}
table(euro2022data$match_id)
```

```{r}
match1 <- euro2020data %>%
  filter(match_id == 3795220)
```

```{r}
trackball <- match1 %>%
  select(c("timestamp", "location"))

trackball <- trackball[!duplicated(trackball), ] %>%
  unnest(location) %>% 
  group_by(timestamp) %>% 
  mutate(key = row_number()) %>% 
  spread(key, location) %>%
  rename(x = "1") %>%
  rename(y = "2") %>%
  select(x,y)

trackball <- trackball %>%
  cbind(row = 1:nrow(trackball))
```

```
write.csv(trackball,"./ball_location_match3795220.csv")
```

```{r}
library(ggplot2)
library(gganimate)
```


```{r}
trackball %>%
  select(x,y,row) %>%
  ggplot(aes(x,y)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  transition_time(row) +
  ease_aes('linear')
```

```{r}
plot(trackball$x,trackball$y)
```

```{r}

```

```{r}
for(i in 1:length(trackball$x)){
  fn <- paste("./",i, sep="")
  png(filename=paste(fn,".png",sep=""))
  plot(trackball$x[i],trackball$y[i], xlim=c(0, 120),ylim=c(0,90))
  dev.off()
}
```

```{r}
p <- trackball[1:100,] %>% ggplot(aes(x,y)) +
  geom_point()
```

```{r}
p + transition_time(row)
```










